# Generated by Django 3.1.3 on 2020-12-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='quantity',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
